import React, { useState } from 'react';
import { 
  CheckCircle2, 
  XCircle, 
  Sparkles, 
  Flame, 
  Layers, 
  Volume2, 
  Clock, 
  FileText, 
  Check, 
  ArrowRight,
  Loader2,
  Film,
  Camera,
  Music
} from 'lucide-react';
import { audioEngine } from '../../audio/audioEngine';

export default function StoryApprovalCard({
  story,
  scenes,
  onApprove,
  onReject,
  threadLanguage = 'English',
  isSubmitting = false
}) {
  const [approvedState, setApprovedState] = useState(null);
  const [showAllScenes, setShowAllScenes] = useState(true);

  if (!story) return null;

  const displayScenes = (scenes && Array.isArray(scenes) && scenes.length > 0) 
    ? scenes 
    : (story.scenes && Array.isArray(story.scenes) ? story.scenes : null);

  const isFinalScenesStage = !!displayScenes;

  const handleApprove = () => {
    audioEngine.playSfx('success');
    setApprovedState('approved');
    onApprove(story.approveUrl);
  };

  const handleReject = () => {
    audioEngine.playSfx('click');
    setApprovedState('rejected');
    onReject(story.cancelUrl);
  };

  return (
    <div className="saas-card animate-float" style={{
      maxWidth: '820px',
      margin: '0 auto 28px auto',
      padding: '24px',
      border: `2px solid ${isFinalScenesStage ? '#10b981' : 'var(--accent-primary)'}`,
      boxShadow: isFinalScenesStage ? '0 12px 40px rgba(16, 185, 129, 0.25)' : '0 12px 40px rgba(99, 102, 241, 0.25)',
      background: 'var(--bg-card)'
    }}>
      {/* Top Banner */}
      <div style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: '16px',
        borderBottom: '1px solid var(--border-subtle)',
        paddingBottom: '12px'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <div style={{
            width: '28px',
            height: '28px',
            borderRadius: '8px',
            background: isFinalScenesStage ? 'linear-gradient(135deg, #10b981, #38bdf8)' : 'var(--grad-gemini)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center'
          }}>
            {isFinalScenesStage ? <Film size={16} color="#ffffff" /> : <Sparkles size={16} color="#ffffff" />}
          </div>
          <div>
            <div className="font-display" style={{ fontSize: '15px', fontWeight: 800, color: 'var(--text-primary)' }}>
              {isFinalScenesStage ? '🎬 Final 5-Scene Production Prompts Ready for Approval' : '⚡ AI Story Ready for Review & Approval'}
            </div>
            <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
              {isFinalScenesStage 
                ? 'Generated by Split Scenes Engine • Review all 5 scene prompts before rendering' 
                : 'Generated by n8n Strategy Engine & Topic Analyzer • 75s (5 Scenes)'}
            </div>
          </div>
        </div>

        <span className={`badge ${isFinalScenesStage ? 'badge-cyan' : 'badge-brand'}`} style={{ fontSize: '11px' }}>
          {isFinalScenesStage ? '✓ 5 Final Scenes' : '⚡ 1-Tap Review'}
        </span>
      </div>

      {/* Meta Specs Grid */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))',
        gap: '8px',
        marginBottom: '18px'
      }}>
        <div style={{ background: 'var(--bg-input)', padding: '8px 12px', borderRadius: '10px', border: '1px solid var(--border-subtle)' }}>
          <div style={{ fontSize: '10.5px', color: 'var(--text-muted)', fontWeight: 700 }}>🎭 GENRE / TOPIC</div>
          <div style={{ fontSize: '12.5px', fontWeight: 700, color: 'var(--text-primary)', textTransform: 'capitalize' }}>
            {story.genre || story.category || story.topic || 'Viral Story'}
          </div>
        </div>

        <div style={{ background: 'var(--bg-input)', padding: '8px 12px', borderRadius: '10px', border: '1px solid var(--border-subtle)' }}>
          <div style={{ fontSize: '10.5px', color: 'var(--text-muted)', fontWeight: 700 }}>🎨 VISUAL STYLE</div>
          <div style={{ fontSize: '12.5px', fontWeight: 700, color: 'var(--accent-cyan)' }}>
            {story.visualStyle || 'Cinematic Realistic'}
          </div>
        </div>

        <div style={{ background: 'var(--bg-input)', padding: '8px 12px', borderRadius: '10px', border: '1px solid var(--border-subtle)' }}>
          <div style={{ fontSize: '10.5px', color: 'var(--text-muted)', fontWeight: 700 }}>🗣 LANGUAGE</div>
          <div style={{ fontSize: '12.5px', fontWeight: 700, color: '#10b981' }}>
            {story.language || threadLanguage || 'English'}
          </div>
        </div>

        <div style={{ background: 'var(--bg-input)', padding: '8px 12px', borderRadius: '10px', border: '1px solid var(--border-subtle)' }}>
          <div style={{ fontSize: '10.5px', color: 'var(--text-muted)', fontWeight: 700 }}>⏱ PACING</div>
          <div style={{ fontSize: '12.5px', fontWeight: 700, color: '#f59e0b' }}>
            {story.duration || '75s (5 Scenes × 15s)'}
          </div>
        </div>
      </div>

      {/* Suggested Title */}
      <div style={{ marginBottom: '14px' }}>
        <div style={{ fontSize: '11px', color: 'var(--text-muted)', fontWeight: 700, textTransform: 'uppercase', marginBottom: '4px' }}>
          📖 Title:
        </div>
        <div className="font-display" style={{
          fontSize: '16px',
          fontWeight: 800,
          color: 'var(--text-primary)',
          background: 'var(--bg-input)',
          padding: '10px 14px',
          borderRadius: '12px',
          border: '1px solid var(--border-subtle)'
        }}>
          {story.suggestedTitle || story.title || 'Untitled Viral Short'}
        </div>
      </div>

      {/* Viral Hook */}
      {story.viralHook && (
        <div style={{ marginBottom: '14px' }}>
          <div style={{ fontSize: '11px', color: '#f59e0b', fontWeight: 700, textTransform: 'uppercase', marginBottom: '4px', display: 'flex', alignItems: 'center', gap: '4px' }}>
            <Flame size={12} /> 3-Second Viral Hook:
          </div>
          <div style={{
            fontSize: '13.5px',
            fontWeight: 600,
            color: 'var(--text-primary)',
            background: 'rgba(245, 158, 11, 0.08)',
            padding: '10px 14px',
            borderRadius: '12px',
            border: '1px solid rgba(245, 158, 11, 0.25)',
            lineHeight: 1.5
          }}>
            "{story.viralHook}"
          </div>
        </div>
      )}

      {/* ─── STAGE 2: 5 FINAL GENERATED SCENES ACCORDION/GRID ─────── */}
      {displayScenes && (
        <div style={{ marginBottom: '18px' }}>
          <div style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            marginBottom: '8px'
          }}>
            <div style={{ fontSize: '11px', color: 'var(--accent-primary)', fontWeight: 800, textTransform: 'uppercase', display: 'flex', alignItems: 'center', gap: '4px' }}>
              <Layers size={13} /> Final 5 Scene Prompts (Split Scenes Output):
            </div>
            <button
              type="button"
              onClick={() => setShowAllScenes(!showAllScenes)}
              style={{
                background: 'none',
                border: 'none',
                color: 'var(--accent-cyan)',
                fontSize: '11.5px',
                fontWeight: 700,
                cursor: 'pointer'
              }}
            >
              {showAllScenes ? 'Hide Details ▲' : 'Show All 5 Scenes ▼'}
            </button>
          </div>

          {showAllScenes && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
              {displayScenes.map((s, idx) => (
                <div
                  key={idx}
                  style={{
                    background: 'var(--bg-input)',
                    borderRadius: '12px',
                    padding: '12px 14px',
                    border: '1px solid var(--border-subtle)'
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '6px' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                      <span className="badge badge-brand" style={{ fontSize: '10.5px', padding: '2px 7px' }}>
                        Scene {s.sceneNumber || idx + 1}
                      </span>
                      <span style={{ fontSize: '11.5px', fontWeight: 700, color: 'var(--text-primary)' }}>
                        {s.act || `Act ${idx + 1}`}
                      </span>
                    </div>
                    <span style={{ fontSize: '11px', color: 'var(--text-muted)', fontFamily: 'monospace' }}>
                      {s.duration || 15}s
                    </span>
                  </div>

                  {/* Voiceover Line */}
                  <div style={{ fontSize: '12.5px', color: 'var(--text-secondary)', marginBottom: '6px', lineHeight: 1.4 }}>
                    <strong style={{ color: 'var(--text-primary)' }}>🗣️ VO:</strong> {s.voiceoverText}
                  </div>

                  {/* Video Prompt */}
                  <div style={{
                    fontSize: '11.5px',
                    color: 'var(--text-muted)',
                    background: 'var(--bg-card)',
                    padding: '8px 10px',
                    borderRadius: '8px',
                    border: '1px solid var(--border-subtle)',
                    fontFamily: 'monospace',
                    lineHeight: 1.4
                  }}>
                    <strong style={{ color: 'var(--accent-cyan)' }}>🎨 Visual Prompt:</strong> {s.videoPrompt}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Story Brief (if not displaying scene cards) */}
      {!displayScenes && story.storyBrief && (
        <div style={{ marginBottom: '20px' }}>
          <div style={{ fontSize: '11px', color: 'var(--text-muted)', fontWeight: 700, textTransform: 'uppercase', marginBottom: '4px', display: 'flex', alignItems: 'center', gap: '4px' }}>
            <FileText size={12} /> 5-Act Narrative Brief:
          </div>
          <div style={{
            fontSize: '12.5px',
            color: 'var(--text-secondary)',
            background: 'var(--bg-input)',
            padding: '12px 14px',
            borderRadius: '12px',
            border: '1px solid var(--border-subtle)',
            whiteSpace: 'pre-line',
            lineHeight: 1.6
          }}>
            {story.storyBrief}
          </div>
        </div>
      )}

      {/* Action Buttons */}
      <div style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'flex-end',
        gap: '12px',
        borderTop: '1px solid var(--border-subtle)',
        paddingTop: '16px'
      }}>
        <button
          type="button"
          onClick={handleReject}
          disabled={approvedState !== null || isSubmitting}
          className="btn-outline"
          style={{
            borderColor: 'rgba(239, 68, 68, 0.4)',
            color: '#ef4444',
            fontSize: '13px',
            padding: '8px 18px',
            gap: '6px'
          }}
        >
          <XCircle size={15} />
          <span>Cancel & Try New Angle</span>
        </button>

        <button
          type="button"
          onClick={handleApprove}
          disabled={approvedState !== null || isSubmitting}
          className="btn-glow"
          style={{
            background: isFinalScenesStage ? 'linear-gradient(135deg, #10b981, #059669)' : 'var(--grad-primary)',
            fontSize: '13px',
            padding: '8px 22px',
            gap: '8px'
          }}
        >
          {approvedState === 'approved' ? (
            <>
              <Check size={16} />
              <span>Approved! Rendering Video...</span>
            </>
          ) : (
            <>
              <CheckCircle2 size={16} />
              <span>{isFinalScenesStage ? 'Approve 5 Scenes & Render Video' : 'Approve Story & Generate 5 Scenes'}</span>
              <ArrowRight size={14} />
            </>
          )}
        </button>
      </div>
    </div>
  );
}
