import React, { useState } from 'react';
import { 
  CheckCircle2, 
  XCircle, 
  Sparkles, 
  Flame, 
  Layers, 
  Volume2, 
  Clock, 
  FileText, 
  Check, 
  ArrowRight,
  Loader2,
  Film,
  Wand2,
  ChevronDown,
  ChevronUp,
  Zap,
  Tag
} from 'lucide-react';
import { audioEngine } from '../../audio/audioEngine';

export default function StoryApprovalCard({
  story,
  scenes,
  onApprove,
  onReject,
  onRefine,
  threadLanguage = 'English',
  isSubmitting = false
}) {
  const [approvedState, setApprovedState] = useState(null);
  const [showAllScenes, setShowAllScenes] = useState(true);
  const [isRefineOpen, setIsRefineOpen] = useState(false);
  const [refineText, setRefineText] = useState('');
  const [isRefining, setIsRefining] = useState(false);

  if (!story) return null;

  const displayScenes = (scenes && Array.isArray(scenes) && scenes.length > 0) 
    ? scenes 
    : (story.scenes && Array.isArray(story.scenes) ? story.scenes : null);

  const isFinalScenesStage = !!displayScenes;

  const handleApprove = () => {
    audioEngine.playSfx('success');
    setApprovedState('approved');
    onApprove(story.approveUrl);
  };

  const handleReject = () => {
    audioEngine.playSfx('click');
    setApprovedState('rejected');
    onReject(story.cancelUrl);
  };

  const handleRefineSubmit = (e) => {
    if (e) e.preventDefault();
    if (!refineText.trim() || isRefining) return;

    audioEngine.playSfx('shimmer');
    setIsRefining(true);
    if (typeof onRefine === 'function') {
      onRefine(refineText.trim(), isFinalScenesStage ? 'REFINE_SCENES' : 'REFINE_STORY');
    }
  };

  const applyChip = (chipText) => {
    audioEngine.playSfx('click');
    setRefineText(prev => prev ? `${prev} ${chipText}` : chipText);
  };

  return (
    <div className="saas-card animate-float" style={{
      maxWidth: '820px',
      margin: '0 auto 28px auto',
      padding: '24px',
      border: `2px solid ${isFinalScenesStage ? '#10b981' : 'var(--accent-primary)'}`,
      boxShadow: isFinalScenesStage ? '0 12px 40px rgba(16, 185, 129, 0.25)' : '0 12px 40px rgba(99, 102, 241, 0.25)',
      background: 'var(--bg-card)',
      borderRadius: '20px'
    }}>
      {/* Top Banner */}
      <div style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: '16px',
        borderBottom: '1px solid var(--border-subtle)',
        paddingBottom: '12px'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <div style={{
            width: '28px',
            height: '28px',
            borderRadius: '8px',
            background: isFinalScenesStage ? 'linear-gradient(135deg, #10b981, #38bdf8)' : 'var(--grad-gemini)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center'
          }}>
            {isFinalScenesStage ? <Film size={16} color="#ffffff" /> : <Sparkles size={16} color="#ffffff" />}
          </div>
          <div>
            <div className="font-display" style={{ fontSize: '15px', fontWeight: 800, color: 'var(--text-primary)' }}>
              {isFinalScenesStage ? '🎬 Final 5-Scene Production Prompts Ready for Approval' : '⚡ AI Story Ready for Review & Approval'}
            </div>
            <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
              {isFinalScenesStage 
                ? 'Generated by Split Scenes Engine • Review all 5 scene prompts or refine with AI before rendering' 
                : 'Generated by n8n Strategy Engine • 75s (5 Scenes) • Approve or refine below'}
            </div>
          </div>
        </div>

        <span className={`badge ${isFinalScenesStage ? 'badge-cyan' : 'badge-brand'}`} style={{ fontSize: '11px' }}>
          {isFinalScenesStage ? '✓ 5 Final Scenes' : '⚡ 1-Tap Review'}
        </span>
      </div>

      {/* Meta Specs Grid */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(130px, 1fr))',
        gap: '10px',
        marginBottom: '16px'
      }}>
        <div style={{ background: 'var(--bg-input)', padding: '8px 12px', borderRadius: '10px', border: '1px solid var(--border-subtle)' }}>
          <div style={{ fontSize: '10.5px', color: 'var(--text-muted)', fontWeight: 600, textTransform: 'uppercase' }}>Genre / Format</div>
          <div style={{ fontSize: '12.5px', fontWeight: 700, color: 'var(--text-primary)', marginTop: '2px' }}>
            {story.genre || story.category || 'Viral Short'}
          </div>
        </div>

        <div style={{ background: 'var(--bg-input)', padding: '8px 12px', borderRadius: '10px', border: '1px solid var(--border-subtle)' }}>
          <div style={{ fontSize: '10.5px', color: 'var(--text-muted)', fontWeight: 600, textTransform: 'uppercase' }}>Pacing & Structure</div>
          <div style={{ fontSize: '12.5px', fontWeight: 700, color: '#38bdf8', marginTop: '2px' }}>
            5 Acts • 75s Total
          </div>
        </div>

        <div style={{ background: 'var(--bg-input)', padding: '8px 12px', borderRadius: '10px', border: '1px solid var(--border-subtle)' }}>
          <div style={{ fontSize: '10.5px', color: 'var(--text-muted)', fontWeight: 600, textTransform: 'uppercase' }}>Language</div>
          <div style={{ fontSize: '12.5px', fontWeight: 700, color: '#10b981', marginTop: '2px' }}>
            {story.language || threadLanguage || 'English'}
          </div>
        </div>

        <div style={{ background: 'var(--bg-input)', padding: '8px 12px', borderRadius: '10px', border: '1px solid var(--border-subtle)' }}>
          <div style={{ fontSize: '10.5px', color: 'var(--text-muted)', fontWeight: 600, textTransform: 'uppercase' }}>Visual Style</div>
          <div style={{ fontSize: '12.5px', fontWeight: 700, color: '#f59e0b', marginTop: '2px' }}>
            {story.visualStyle || 'Cinematic'}
          </div>
        </div>
      </div>

      {/* Suggested Title */}
      <div style={{ marginBottom: '14px' }}>
        <div style={{ fontSize: '11px', color: 'var(--text-muted)', fontWeight: 700, textTransform: 'uppercase', marginBottom: '4px' }}>
          Suggested Video Title:
        </div>
        <div style={{
          fontSize: '15px',
          fontWeight: 800,
          color: 'var(--text-primary)',
          background: 'var(--bg-input)',
          padding: '10px 14px',
          borderRadius: '10px',
          border: '1px solid var(--border-subtle)',
          display: 'flex',
          alignItems: 'center',
          gap: '8px'
        }}>
          <span>🔥</span>
          <span>{story.suggestedTitle || story.title}</span>
        </div>
      </div>

      {/* Viral Hook (First 3 Seconds) */}
      {story.viralHook && (
        <div style={{ marginBottom: '16px' }}>
          <div style={{ fontSize: '11px', color: '#f59e0b', fontWeight: 700, textTransform: 'uppercase', marginBottom: '4px', display: 'flex', alignItems: 'center', gap: '4px' }}>
            <Flame size={12} /> Viral Hook (First 3 Seconds):
          </div>
          <div style={{
            fontSize: '13px',
            fontWeight: 600,
            color: 'var(--text-primary)',
            background: 'rgba(245, 158, 11, 0.08)',
            padding: '10px 14px',
            borderRadius: '10px',
            border: '1px solid rgba(245, 158, 11, 0.25)',
            lineHeight: 1.5
          }}>
            "{story.viralHook}"
          </div>
        </div>
      )}

      {/* Scene Cards View (Stage 2) */}
      {displayScenes && (
        <div style={{ marginBottom: '20px' }}>
          <div style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            marginBottom: '10px'
          }}>
            <div style={{ fontSize: '12px', fontWeight: 700, color: 'var(--text-primary)', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <Layers size={14} color="#10b981" />
              <span>Full 5-Scene Master Screenplay ({displayScenes.length} Scenes)</span>
            </div>
            <button
              type="button"
              onClick={() => setShowAllScenes(!showAllScenes)}
              style={{
                background: 'transparent',
                border: 'none',
                color: 'var(--text-muted)',
                fontSize: '11.5px',
                cursor: 'pointer',
                fontWeight: 600
              }}
            >
              {showAllScenes ? 'Collapse' : 'Expand All'}
            </button>
          </div>

          {showAllScenes && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
              {displayScenes.map((s, idx) => (
                <div
                  key={idx}
                  style={{
                    background: 'var(--bg-input)',
                    borderRadius: '12px',
                    padding: '12px 14px',
                    border: '1px solid var(--border-subtle)'
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '6px' }}>
                    <span className="badge badge-brand" style={{ fontSize: '10.5px' }}>
                      Scene {idx + 1} of 5 • {s.duration || 15}s
                    </span>
                    <span style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
                      {(s.voiceoverText || '').length} characters
                    </span>
                  </div>

                  <div style={{ fontSize: '13px', color: 'var(--text-primary)', marginBottom: '8px', lineHeight: 1.5 }}>
                    <strong>🎙️ Voiceover:</strong> "{s.voiceoverText}"
                  </div>

                  <div style={{
                    fontSize: '11px',
                    color: 'var(--text-muted)',
                    background: 'rgba(0,0,0,0.2)',
                    padding: '8px 10px',
                    borderRadius: '8px',
                    lineHeight: 1.4
                  }}>
                    <strong style={{ color: 'var(--accent-cyan)' }}>🎨 Visual Prompt:</strong> {s.videoPrompt}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Story Brief (Stage 1) */}
      {!displayScenes && story.storyBrief && (
        <div style={{ marginBottom: '20px' }}>
          <div style={{ fontSize: '11px', color: 'var(--text-muted)', fontWeight: 700, textTransform: 'uppercase', marginBottom: '4px', display: 'flex', alignItems: 'center', gap: '4px' }}>
            <FileText size={12} /> 5-Act Narrative Brief:
          </div>
          <div style={{
            fontSize: '12.5px',
            color: 'var(--text-secondary)',
            background: 'var(--bg-input)',
            padding: '12px 14px',
            borderRadius: '12px',
            border: '1px solid var(--border-subtle)',
            whiteSpace: 'pre-line',
            lineHeight: 1.6
          }}>
            {story.storyBrief}
          </div>
        </div>
      )}

      {/* ─── INLINE AI AGENT REFINEMENT DRAWER ─────────────────────── */}
      <div style={{
        marginBottom: '16px',
        borderRadius: '14px',
        border: '1px solid var(--border-subtle)',
        background: isRefineOpen ? 'rgba(236, 72, 153, 0.04)' : 'transparent',
        overflow: 'hidden',
        transition: 'all 0.2s ease'
      }}>
        <button
          type="button"
          onClick={() => setIsRefineOpen(!isRefineOpen)}
          style={{
            width: '100%',
            padding: '10px 14px',
            background: 'transparent',
            border: 'none',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            cursor: 'pointer',
            color: '#ec4899',
            fontSize: '12.5px',
            fontWeight: 700
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
            <Wand2 size={14} />
            <span>{isFinalScenesStage ? '✍️ Refine 5-Scene Screenplay with AI Doctor' : '✍️ Refine Story Brief with AI Doctor'}</span>
          </div>
          {isRefineOpen ? <ChevronUp size={15} /> : <ChevronDown size={15} />}
        </button>

        {isRefineOpen && (
          <form onSubmit={handleRefineSubmit} style={{ padding: '0 14px 14px 14px' }}>
            {/* Quick Chips */}
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px', marginBottom: '10px' }}>
              <button
                type="button"
                onClick={() => applyChip('Make the 3-second hook punchier and more urgent.')}
                className="btn-outline"
                style={{ fontSize: '11px', padding: '3px 8px', borderRadius: '99px' }}
              >
                ⚡ Punchier Hook
              </button>
              <button
                type="button"
                onClick={() => applyChip('Add an unpredictable shocking plot twist before the climax.')}
                className="btn-outline"
                style={{ fontSize: '11px', padding: '3px 8px', borderRadius: '99px' }}
              >
                🌀 Shocking Twist
              </button>
              <button
                type="button"
                onClick={() => applyChip('Make the tone darker, cinematic and more intense.')}
                className="btn-outline"
                style={{ fontSize: '11px', padding: '3px 8px', borderRadius: '99px' }}
              >
                🎭 Darker Tone
              </button>
              <button
                type="button"
                onClick={() => applyChip('Increase 3-second retention with rapid pacing.')}
                className="btn-outline"
                style={{ fontSize: '11px', padding: '3px 8px', borderRadius: '99px' }}
              >
                📈 Boost Retention
              </button>
            </div>

            {/* Custom Refine Textarea */}
            <div style={{ position: 'relative', marginBottom: '10px' }}>
              <textarea
                value={refineText}
                onChange={(e) => setRefineText(e.target.value)}
                placeholder={isFinalScenesStage 
                  ? "Describe scene adjustments... (e.g. 'Change Scene 3 camera prompt to aerial drone shot and make scene 5 voiceover more dramatic')"
                  : "Tell AI Doctor what to refine... (e.g. 'Make the ending more emotional and focus on the secret discovery')"
                }
                rows={2}
                style={{
                  width: '100%',
                  background: 'var(--bg-input)',
                  border: '1px solid var(--border-medium)',
                  borderRadius: '10px',
                  padding: '10px 12px',
                  color: 'var(--text-primary)',
                  fontSize: '13px',
                  lineHeight: 1.4,
                  resize: 'none',
                  outline: 'none'
                }}
              />
            </div>

            <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
              <button
                type="submit"
                disabled={!refineText.trim() || isRefining}
                className="btn-glow"
                style={{
                  background: 'linear-gradient(135deg, #ec4899, #8b5cf6)',
                  fontSize: '12px',
                  padding: '6px 16px',
                  gap: '6px',
                  opacity: !refineText.trim() || isRefining ? 0.6 : 1,
                  cursor: !refineText.trim() || isRefining ? 'not-allowed' : 'pointer'
                }}
              >
                {isRefining ? <Loader2 size={13} className="animate-spin" /> : <Wand2 size={13} />}
                <span>{isRefining ? 'Refining with AI Agent...' : 'Send Refine Instruction to n8n'}</span>
              </button>
            </div>
          </form>
        )}
      </div>

      {/* Main Action Buttons */}
      <div style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        flexWrap: 'wrap',
        gap: '12px',
        borderTop: '1px solid var(--border-subtle)',
        paddingTop: '16px'
      }}>
        <button
          type="button"
          onClick={handleReject}
          disabled={approvedState !== null || isSubmitting}
          className="btn-outline"
          style={{
            borderColor: 'rgba(239, 68, 68, 0.4)',
            color: '#ef4444',
            fontSize: '13px',
            padding: '8px 18px',
            gap: '6px'
          }}
        >
          <XCircle size={15} />
          <span>Cancel & Terminate</span>
        </button>

        <button
          type="button"
          onClick={handleApprove}
          disabled={approvedState !== null || isSubmitting}
          className="btn-glow"
          style={{
            background: isFinalScenesStage ? 'linear-gradient(135deg, #10b981, #059669)' : 'var(--grad-primary)',
            fontSize: '13px',
            padding: '8px 22px',
            gap: '8px'
          }}
        >
          {approvedState === 'approved' ? (
            <>
              <Check size={16} />
              <span>{isFinalScenesStage ? 'Approved! Rendering Video...' : 'Approved! Generating Scenes...'}</span>
            </>
          ) : (
            <>
              <CheckCircle2 size={16} />
              <span>{isFinalScenesStage ? 'Approve 5 Scenes & Render Video' : 'Approve Story & Generate 5 Scenes'}</span>
              <ArrowRight size={14} />
            </>
          )}
        </button>
      </div>
    </div>
  );
}
