import React, { useState } from 'react';
import { 
  CheckCircle2, 
  XCircle, 
  Sparkles, 
  Flame, 
  Layers, 
  Volume2, 
  Clock, 
  FileText, 
  Check, 
  ArrowRight,
  Loader2
} from 'lucide-react';
import { audioEngine } from '../../audio/audioEngine';

export default function StoryApprovalCard({
  story,
  onApprove,
  onReject,
  isSubmitting = false
}) {
  const [approvedState, setApprovedState] = useState(null);

  if (!story) return null;

  const handleApprove = () => {
    audioEngine.playSfx('success');
    setApprovedState('approved');
    onApprove(story.approveUrl);
  };

  const handleReject = () => {
    audioEngine.playSfx('click');
    setApprovedState('rejected');
    onReject(story.cancelUrl);
  };

  return (
    <div className="saas-card animate-float" style={{
      maxWidth: '820px',
      margin: '0 auto 28px auto',
      padding: '24px',
      border: '2px solid var(--accent-primary)',
      boxShadow: '0 12px 40px rgba(99, 102, 241, 0.25)',
      background: 'var(--bg-card)'
    }}>
      {/* Top Banner */}
      <div style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: '16px',
        borderBottom: '1px solid var(--border-subtle)',
        paddingBottom: '12px'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <div style={{
            width: '28px',
            height: '28px',
            borderRadius: '8px',
            background: 'var(--grad-gemini)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center'
          }}>
            <Sparkles size={16} color="#ffffff" />
          </div>
          <div>
            <div className="font-display" style={{ fontSize: '15px', fontWeight: 800, color: 'var(--text-primary)' }}>
              AI Story Ready for Review & Approval
            </div>
            <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
              Generated by n8n Strategy Engine & Topic Analyzer • 75s (5 Scenes)
            </div>
          </div>
        </div>

        <span className="badge badge-cyan" style={{ fontSize: '11px' }}>
          ⚡ 1-Tap Approval
        </span>
      </div>

      {/* Meta Specs Grid */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))',
        gap: '8px',
        marginBottom: '18px'
      }}>
        <div style={{ background: 'var(--bg-input)', padding: '8px 12px', borderRadius: '10px', border: '1px solid var(--border-subtle)' }}>
          <div style={{ fontSize: '10.5px', color: 'var(--text-muted)', fontWeight: 700 }}>🎭 GENRE / TOPIC</div>
          <div style={{ fontSize: '12.5px', fontWeight: 700, color: 'var(--text-primary)', textTransform: 'capitalize' }}>
            {story.genre || story.topic || 'Viral Story'}
          </div>
        </div>

        <div style={{ background: 'var(--bg-input)', padding: '8px 12px', borderRadius: '10px', border: '1px solid var(--border-subtle)' }}>
          <div style={{ fontSize: '10.5px', color: 'var(--text-muted)', fontWeight: 700 }}>🎨 VISUAL STYLE</div>
          <div style={{ fontSize: '12.5px', fontWeight: 700, color: 'var(--accent-cyan)' }}>
            {story.visualStyle || 'Cinematic Realistic'}
          </div>
        </div>

        <div style={{ background: 'var(--bg-input)', padding: '8px 12px', borderRadius: '10px', border: '1px solid var(--border-subtle)' }}>
          <div style={{ fontSize: '10.5px', color: 'var(--text-muted)', fontWeight: 700 }}>🗣 LANGUAGE</div>
          <div style={{ fontSize: '12.5px', fontWeight: 700, color: '#10b981' }}>
            {story.language || 'Hinglish'}
          </div>
        </div>

        <div style={{ background: 'var(--bg-input)', padding: '8px 12px', borderRadius: '10px', border: '1px solid var(--border-subtle)' }}>
          <div style={{ fontSize: '10.5px', color: 'var(--text-muted)', fontWeight: 700 }}>⏱ PACING</div>
          <div style={{ fontSize: '12.5px', fontWeight: 700, color: '#f59e0b' }}>
            {story.duration || '75s (5 Scenes × 15s)'}
          </div>
        </div>
      </div>

      {/* Suggested Title */}
      <div style={{ marginBottom: '14px' }}>
        <div style={{ fontSize: '11px', color: 'var(--text-muted)', fontWeight: 700, textTransform: 'uppercase', marginBottom: '4px' }}>
          📖 Suggested Title:
        </div>
        <div className="font-display" style={{
          fontSize: '16px',
          fontWeight: 800,
          color: 'var(--text-primary)',
          background: 'var(--bg-input)',
          padding: '10px 14px',
          borderRadius: '12px',
          border: '1px solid var(--border-subtle)'
        }}>
          {story.suggestedTitle || story.title || 'Untitled Viral Short'}
        </div>
      </div>

      {/* Viral Hook */}
      {story.viralHook && (
        <div style={{ marginBottom: '14px' }}>
          <div style={{ fontSize: '11px', color: 'var(--text-muted)', fontWeight: 700, textTransform: 'uppercase', marginBottom: '4px' }}>
            🎯 3-Second Viral Hook:
          </div>
          <div style={{
            fontSize: '13.5px',
            fontStyle: 'italic',
            color: '#38bdf8',
            background: 'rgba(56, 189, 248, 0.08)',
            padding: '10px 14px',
            borderRadius: '12px',
            border: '1px solid rgba(56, 189, 248, 0.25)'
          }}>
            "{story.viralHook}"
          </div>
        </div>
      )}

      {/* Story Brief */}
      {story.storyBrief && (
        <div style={{ marginBottom: '20px' }}>
          <div style={{ fontSize: '11px', color: 'var(--text-muted)', fontWeight: 700, textTransform: 'uppercase', marginBottom: '4px' }}>
            📝 5-Act Story Arc Brief:
          </div>
          <div style={{
            fontSize: '13px',
            color: 'var(--text-secondary)',
            lineHeight: 1.6,
            background: 'var(--bg-input)',
            padding: '12px 14px',
            borderRadius: '12px',
            border: '1px solid var(--border-subtle)',
            whiteSpace: 'pre-line'
          }}>
            {story.storyBrief}
          </div>
        </div>
      )}

      {/* Action Buttons */}
      <div style={{
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        borderTop: '1px solid var(--border-subtle)',
        paddingTop: '16px'
      }}>
        {approvedState === 'approved' ? (
          <div style={{
            width: '100%',
            background: 'rgba(16, 185, 129, 0.15)',
            border: '1px solid #10b981',
            borderRadius: '12px',
            padding: '12px',
            textAlign: 'center',
            color: '#10b981',
            fontWeight: 800,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            gap: '8px'
          }}>
            <CheckCircle2 size={20} />
            <span>Story Approved! n8n is generating 5-scene video clips...</span>
          </div>
        ) : approvedState === 'rejected' ? (
          <div style={{
            width: '100%',
            background: 'rgba(239, 68, 68, 0.15)',
            border: '1px solid #ef4444',
            borderRadius: '12px',
            padding: '12px',
            textAlign: 'center',
            color: '#ef4444',
            fontWeight: 800,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            gap: '8px'
          }}>
            <XCircle size={20} />
            <span>Story Generation Cancelled.</span>
          </div>
        ) : (
          <>
            <button
              onClick={handleApprove}
              disabled={isSubmitting}
              className="btn-glow"
              style={{
                flex: 1.4,
                padding: '14px 20px',
                fontSize: '14.5px',
                justifyContent: 'center',
                background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
                boxShadow: '0 4px 20px rgba(16, 185, 129, 0.4)'
              }}
            >
              {isSubmitting ? (
                <Loader2 size={18} className="spin-animation" />
              ) : (
                <CheckCircle2 size={18} />
              )}
              <span>✅ Approve & Start 5-Scene Video Generation</span>
            </button>

            <button
              onClick={handleReject}
              disabled={isSubmitting}
              className="btn-outline"
              style={{
                flex: 0.6,
                padding: '14px 16px',
                fontSize: '13.5px',
                justifyContent: 'center',
                color: '#ef4444',
                borderColor: 'rgba(239, 68, 68, 0.3)'
              }}
            >
              <XCircle size={16} />
              <span>Cancel</span>
            </button>
          </>
        )}
      </div>
    </div>
  );
}
